"""initial schema

Revision ID: 1ee86fa50fef
Revises: 
Create Date: 2026-07-21 10:12:56.270680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee86fa50fef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    # Hand-added: this is the schema as it stood when Alembic was adopted, and
    # the next revision drops it. Without it a fresh database fails on that drop.
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('ai_reply', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(length=32), nullable=True),
    sa.Column('wins', sa.Text(), nullable=True),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_created_at'), 'entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_table('mantras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantras_created_at'), 'mantras', ['created_at'], unique=False)
    op.create_index(op.f('ix_mantras_user_id'), 'mantras', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_index(op.f('ix_mantras_user_id'), table_name='mantras')
    op.drop_index(op.f('ix_mantras_created_at'), table_name='mantras')
    op.drop_table('mantras')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_created_at'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
